
; function to generate n uniform random samples 
; on the sensitive domain for a faraday cup
; measurement.
;
; INPUTS
; zlower        lower limit in speed (vz) for the window
; zupper        upper limit in speed (vz) for the window
; alpha_rad     maximum inflow angle to which the cup is sensitive
; n             number of samples desired (default 1000)
;
; OUTPUT anonymous structure containing:
; phi           phi angles (deflection x_FC=0) for each sample
; theta         theta angles (deflection y_FC=0)
; r             radial speed
; dvol          differential volume in phase space assigned to each sample
; zlower        [echo from input]
; zupper        [echo from input]
; alpha_rad     [echo from input]
function uniform_sample_frustum, zlower, zupper, alpha_rad, n=n
  if n_elements(n) eq 0 then n = 1000.
  
  z0 = zlower
  dz0 = zupper - zlower
  r0 = z0*tan(alpha_rad)
  r1 = (z0+dz0)*tan(alpha_rad)
  
  ; draw points from the rectangular prism
  ; that circumscribes the domain:
  ; (a) calculate the ratio of volumes and adjust the number of 
  ; samples
  vol = (dz0*!pi/3.)*(r0^2 + r1^2 + r0*r1)
  recvol = dz0*(2.*r1)^2
  n0 = 1.1*n*recvol/vol
  ; (b) generate uniform points on the prism
  xrand = 2.*r1*(randomu(seed, n0) - 0.5)
  yrand = 2.*r1*(randomu(seed, n0) - 0.5)
  zrand = z0 + dz0*randomu(seed, n0)
  ; (c) select for points inside the domain 
  tanalpha_rad = sqrt(xrand^2 + yrand^2)/zrand
  inside = where(tanalpha_rad lt tan(alpha_rad), nin)
  inside = inside[0: (nin<n)-1]
  x = xrand[inside]
  y = yrand[inside]
  z = zrand[inside]

  ; calculate polar coordinates and differential volume elements
  phi = atan(x, z)
  theta = atan(y,z)
  r = sqrt(x^2 + y^2 + z^2)
  dvol = vol/n + (0.*r)

  ; package output structure
  return, {phi:phi, theta:theta, r:r, dvol:dvol, zlower:zlower, zupper:zupper, alpha_rad:alpha_rad}

end



; function to rescale the set of samples generated by uniform_sample_frustum(),
; and their associated differentials to a new modulator window
; without changing their polar angle. 
; 
; The advantage of using this function is that the samples can be recycled without
; additional calls to the random number generator or the cup geometrical response.
; 
; The disadvantage is that the new domain is not uniformly sampled.
; 
; INPUTS
; zlower        lower limit in speed (vz) for the window
; zupper        upper limit in speed (vz) for the window
; input         anonymous structure as generated by uniform_sample_frustum()
;
; OUTPUT anonymous structure containing:
; phi           phi angles (deflection x_FC=0) for each sample
; theta         theta angles (deflection y_FC=0)
; r             radial speed
; dvol          differential volume in phase space assigned to each sample
; zlower        [echo from input structure]
; zupper        [echo from input structure]
; alpha_rad     [echo from input structure]
function rescale_frustum_samples, zlower, zupper, input, debug=debug

  cosalpha = 1./sqrt( tan(input.phi)^2 + tan(input.theta)^2 + 1.)
  tanalpha_max = tan(input.alpha_rad)
  z0 = input.r*cosalpha
  x0 = tan(input.phi) * z0
  y0 = tan(input.theta) * z0
  zlo0 = input.zlower
  dz0 = input.zupper - input.zlower

  ; find scale factor for z position in the old frustum
  lamda = (z0 - zlo0)/dz0

  ; calculate the new z coordinate by rescaling
  dz1 = zupper - zlower
  newz = zlower + dz1*lamda
  newr = newz/cosalpha

  ; rescale the volume element
  newdvol = input.dvol*(dz1/dz0)*(newr/input.r)^2

  if keyword_set(debug) then begin
    ; perform consistency check:
    radius0 = zlower*tanalpha_max
    radius1 = zupper*tanalpha_max
    newvol = (dz1*!pi/3.)*(radius0^2 + radius1^2 + radius0*radius1)
    print, 'net volume transform error: ', 100.*(total(newdvol) - newvol)/newvol, '%'
  endif

  return, {phi:input.phi, theta:input.theta, r:newr, dvol:newdvol, $
           zlower:zlower, zupper:zupper, alpha_rad:input.alpha_rad}

end

function rays_to_xyzfc, input
  cosalpha = 1./sqrt( tan(input.phi)^2 + tan(input.theta)^2 + 1.)
  z0 = input.r*cosalpha
  x0 = tan(input.phi) * z0
  y0 = tan(input.theta) * z0
  return, [[x0], [y0], [z0]]
end

; wrapper for the spc geometry function 
function calculate_effective_area_cm2, phi_rad, theta_rad
  ; spc function takes arguments in degrees and returns sensitive area in mm^2
  return, 100.*psp_swp_spc_coldspot(phi_rad/!dtor, theta_rad/!dtor)
end

function cup_response_numflux_1step, vz_lo, vz_hi, fv, effarea, ps_samples
  nsensors = (size(effarea, /dim))[0]
  numflux = fltarr(nsensors)
  ps_samples = rescale_frustum_samples(vz_lo, vz_hi, ps_samples)
  vxyz = rays_to_xyzfc(ps_samples)
  f = fv.evaluate(vxyz)
  ; flux = const*vz * Area * f(v) * d3v
  ; units [const]*[km/s]*[cm2]*[cm-3 km-3 s3]*[km3 s-3] = [const]*[km/cm] s-1 = s-1
  ; so [const] must have units of cm per km
  cmperkm = 1e5
  numflux[0] = cmperkm*total(reform(vxyz[*,2])*reform(effarea[0,*])*f*ps_samples.dvol, /nan)
  numflux[1] = cmperkm*total(reform(vxyz[*,2])*reform(effarea[1,*])*f*ps_samples.dvol, /nan)
  numflux[2] = cmperkm*total(reform(vxyz[*,2])*reform(effarea[2,*])*f*ps_samples.dvol, /nan)
  numflux[3] = cmperkm*total(reform(vxyz[*,2])*reform(effarea[3,*])*f*ps_samples.dvol, /nan)
  return, numflux
end

function cup_response_numflux_spectrum, vz_lo, vz_hi, fv, effarea, ps_samples
  nsensors = (size(effarea, /dim))[0]
  nsteps = n_elements(vz_lo)
  numflux = fltarr(nsensors, nsteps)
  for i = 0, nsteps-1 do numflux[*,i] = cup_response_numflux_1step(vz_lo[i], vz_hi[i], fv, effarea, ps_samples)
  return, numflux
end


function integration_test, debug=debug, n=n, samples = samples, params=params, save=save

; 0. define constants
if n_elements(n) eq 0 then integration_pts = 1000. else integration_pts = n
if n_elements(params) eq 0 then params =  {vx:100., vy:50., vz:250., w:50., n:1000.}
spc_fov_radians = 44.*!dtor

; 1a. set up a vz spectrum range
nsteps = 30
vlo = 100. + 20.*findgen(nsteps)
vhi = vlo+20.

; 1b. initialize an example velocity distribution function
myvdf = new_vdf('maxwellian_vdf', params)

; 2. initialize the samples, i.e.
if n_elements(samples) eq 0 then  $
  ps_samples = uniform_sample_frustum(vlo[0], vhi[0], spc_fov_radians, n=integration_pts) $
  else ps_samples = samples

; 3. calculate the geometric factors
effarea = calculate_effective_area_cm2(ps_samples.phi, ps_samples.theta)

; 4. calculate the responses
numflux = cup_response_numflux_spectrum(vlo, vhi, myvdf, effarea, ps_samples)


if keyword_set(debug) then begin
  !p.multi = [0, 2, 2]
  yrange = minmax(numflux)
  plot, vlo, numflux[0,*], yrange=yrange
  plot, vlo, numflux[1,*], yrange=yrange
  plot, vlo, numflux[2,*], yrange=yrange
  plot, vlo, numflux[3,*], yrange=yrange
  stop
endif
 
if keyword_set(save) then begin
  WRITE_CSV, 'flux_data.csv', numflux, $
    table_header = ['Number flux from fc_fov_sampling.pro:integration_test', $
                   'result = integration_test(n=1000, params =  {vx:100., vy:50., vz:250., w:50., n:1000.})' ,$
                   'mstevens@cfa.harvard.edu, July 15, 2024', $
                   '', '']
endif

return, numflux 
 
end

pro timetest

ns = [10, 33, 100, 333, 1000, 3333, 10000] 
times = 0.*ns
spc_fov_radians = 44.
for j = 0, n_elements(ns)-1 do begin &$
  t0 = systime(/seconds) &$
  n=ns[j] &$
  print, n &$
  samples = uniform_sample_frustum(100., 200., spc_fov_radians, n=n) &$
  for i = 0, 10 do foo = integration_test(n=n, samples = samples) &$
  times[j] = (systime(/seconds)-t0)/10. &$
endfor &$
  
print, dt_1000

t0 = systime(/seconds)
for i = 0, 100 do integration_test, n=100.
dt_100 = (systime(/seconds)-t0)/100.

; the computation time is linear in the number of points

end



pro restest


  ns = [10, 33, 100, 333, 1000, 3333, 10000]
  fluxes = fltarr(4, 30, 7, 10)
  params =  {vx:100., vy:50., vz:150., w:100., n:1000.}
  
  spc_fov_radians = 44.
  for j = 0, n_elements(ns)-1 do begin &$
    n=ns[j] &$
    print, n &$
    for i = 0, 9 do fluxes[*,*,j,i] = integration_test(n=n, params = params) &$
  endfor &$

  means = mean(fluxes, dim = 4)
  meansq = mean(fluxes^2, dim = 4)
  var = sqrt(meansq - means^2)
  pk = max(means[0,*,-1], pkloc)
  y10 = (var/means)[0,pkloc,0]

  p = plot(ns, (var/means)[0,pkloc,*], linestyle = '', symbol = 'o', /xlog, /ylog, xtitle = 'number of integration samples', $
      ytitle = 'proportional error')
  p2 = plot(ns, (var/means)[1,pkloc,*], linestyle = '', symbol = 'o', color = 'blue', /overplot)
  p3 = plot(ns, (var/means)[2,pkloc,*], linestyle = '', symbol = 'o', color = 'green', /overplot)
  p4 = plot(ns, (var/means)[3,pkloc,*], linestyle = '', symbol = 'o', color = 'red', /overplot)
  p5 = plot(ns, y10/sqrt(0.1*ns), linestyle = '- - ', thick = 3, /overplot)
  p.title = 'monte carlo integration on the faraday cup response $\n$ with uniform sampling, Mach=1 case'
  p.xrange = [1, 1e5]
  p.font_size = 14
  p.yrange = [0.01, 10]

  
  
  oplot, ns, 1./sqrt(0.1*ns), color = 254
  oplot, minmax(ns), 0.1+[0,0]
  
  ; the precision goes like n^(-1/2)
  ; for 1% precision, this implies that we would need about 1e6 integration points
  ; that's way too many!
  plot, means[0,*,-1]
  for i = 0, 9 do oplot, fluxes[0,*,-1, i], psym = 1
  
  best = means[*,*,-1]
  diffs = fluxes
  for k = 0, 6 do for l = 0, 9 do diffs[*,*,k,l] = fluxes[*,*,k,l] - means
  !p.multi = 0
  
  plot, ns, abs(fluxes[0,8,*,1] - means[0,8,*]), /xl, /yl
  for j = 0, 9 do oplot, ns, abs(fluxes[0,8,*,j]- means[0,8, *]), psym = 6
  

end
